require('dotenv').config();
const {Client,GatewayIntentBits,REST,Routes,SlashCommandBuilder,PermissionFlagsBits,AttachmentBuilder}=require('discord.js');
const TOKEN=process.env.DISCORD_BOT_TOKEN,CLIENT_ID=process.env.DISCORD_CLIENT_ID,GUILD_ID=process.env.DISCORD_GUILD_ID,DASHBOARD_URL=process.env.DASHBOARD_URL||'http://127.0.0.1:3000';const ADMINS=new Set(String(process.env.DISCORD_ADMIN_USER_IDS||'').split(',').map(x=>x.trim()).filter(Boolean));
if(!TOKEN){console.log('Discord bot disabled: DISCORD_BOT_TOKEN is not configured.');process.exit(0);}if(!CLIENT_ID){console.error('DISCORD_CLIENT_ID is required.');process.exit(1);}
const commands=[
 new SlashCommandBuilder().setName('status').setDescription('自動売買の状態'),new SlashCommandBuilder().setName('on').setDescription('自動売買ON'),new SlashCommandBuilder().setName('off').setDescription('自動売買OFF'),new SlashCommandBuilder().setName('balance').setDescription('残高'),new SlashCommandBuilder().setName('price').setDescription('価格').addStringOption(o=>o.setName('token').setDescription('シンボル').setRequired(false)),
 new SlashCommandBuilder().setName('chart').setDescription('価格チャート画像').addStringOption(o=>o.setName('token').setDescription('監視対象シンボル').setRequired(true)),new SlashCommandBuilder().setName('add-token').setDescription('Arc RPCでERC-20を追加').addStringOption(o=>o.setName('address').setDescription('0x...').setRequired(true)).addStringOption(o=>o.setName('symbol').setDescription('表示名（任意）').setRequired(false)),new SlashCommandBuilder().setName('buzz').setDescription('Xバズり指標').addStringOption(o=>o.setName('token').setDescription('シンボル').setRequired(true)),new SlashCommandBuilder().setName('stop').setDescription('緊急停止'),new SlashCommandBuilder().setName('reset-stop').setDescription('緊急停止解除'),
].map(c=>c.toJSON());
const client=new Client({intents:[GatewayIntentBits.Guilds]});
async function jsonApi(endpoint,options={}){const r=await fetch(`${DASHBOARD_URL}${endpoint}`,{...options,headers:{'content-type':'application/json',...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||`Dashboard API ${r.status}`);return d;}
function reply(content,files){return{content:String(content).slice(0,1900),ephemeral:true,files};}function canManage(i){return ADMINS.has(i.user.id)||Boolean(i.memberPermissions?.has(PermissionFlagsBits.ManageGuild));}
client.once('ready',async c=>{const rest=new REST({version:'10'}).setToken(TOKEN);await rest.put(GUILD_ID?Routes.applicationGuildCommands(CLIENT_ID,GUILD_ID):Routes.applicationCommands(CLIENT_ID),{body:commands});console.log(`Discord bot logged in as ${c.user.tag}`);});
client.on('interactionCreate',async i=>{if(!i.isChatInputCommand())return;try{const n=i.commandName;if(n==='chart'){const symbol=i.options.getString('token',true).toUpperCase();await i.deferReply({ephemeral:true});const r=await fetch(`${DASHBOARD_URL}/api/token/${encodeURIComponent(symbol)}/chart.svg`);if(!r.ok)throw Error(await r.text());const image=Buffer.from(await r.arrayBuffer());return i.editReply({content:`📊 ${symbol} / Arc RPC paper chart`,files:[new AttachmentBuilder(image,{name:`${symbol.toLowerCase()}-chart.svg`})]});}
 if(n==='add-token'){if(!canManage(i))return i.reply({content:'管理権限が必要です。',ephemeral:true});const d=await jsonApi('/api/tokens/import',{method:'POST',body:JSON.stringify({address:i.options.getString('address',true),symbol:i.options.getString('symbol')})});return i.reply({content:`✅ ${d.token} を追加\nContract: ${d.contractAddress}\n${d.meta.name} / decimals ${d.meta.decimals}\n価格: ${d.price??'未設定（ARC_PRICE_ORACLESを設定）'}\n価格源: ${d.meta.priceSource}`,ephemeral:true});}
 if(n==='price'){const d=await jsonApi('/api/prices'),q=i.options.getString('token')?.toUpperCase(),list=q?[[q,d.prices?.[q]]]:Object.entries(d.prices||{});return i.reply({content:list.map(([t,p])=>`${t}: ${p??'未設定'} / volume ${Number(d.volumes?.[t]||0).toLocaleString()}`).join('\n')||'データなし',ephemeral:true});}
 if(n==='buzz'){return i.reply({content:'Xバズりは現在のArc RPC価格機能とは独立した機能です。X_BEARER_TOKENとsocial APIを設定してください。',ephemeral:true});}
 if(!canManage(i))return i.reply({content:'管理権限が必要です。',ephemeral:true});if(n==='on'||n==='off'){const d=await jsonApi('/api/toggle-bot',{method:'POST',body:JSON.stringify({enabled:n==='on'})});return i.reply({content:`自動売買 ${d.botEnabled?'ON':'OFF'}`,ephemeral:true});}if(n==='stop'){await jsonApi('/api/emergency-stop',{method:'POST'});return i.reply({content:'🚨 緊急停止しました。',ephemeral:true});}if(n==='reset-stop'){await jsonApi('/api/emergency-reset',{method:'POST'});return i.reply({content:'緊急停止を解除しました。自動売買はOFFです。',ephemeral:true});}if(n==='status'){const d=await jsonApi('/api/dashboard');return i.reply({content:`状態: ${d.botStatus}\n自動売買: ${d.botEnabled?'ON':'OFF'}\n緊急停止: ${d.emergencyStop?'有効':'無効'}`,ephemeral:true});}
 }catch(e){console.error(`Discord command failed: ${e.message}`);if(i.deferred)return i.editReply({content:`処理に失敗しました: ${e.message}`});return i.reply({content:`処理に失敗しました: ${e.message}`,ephemeral:true});}});client.login(TOKEN);
