const express = require('express');
const fs = require('fs');
const path = require('path');
require('dotenv').config();
const { getArcStatus, isAddress, readErc20, readChainlinkPrice } = require('./arc-readonly');
const app = express(); const PORT = Number(process.env.PORT || 3000); const DATA_DIR = path.join(__dirname, 'data'); const STORE_PATH = path.join(DATA_DIR, 'store.json');
const envTokens = String(process.env.MONITORED_TOKENS || 'BTC,ETH,SOL').split(',').map(x => x.trim().toUpperCase()).filter(Boolean);
const oracleMap = (() => { try { return JSON.parse(process.env.ARC_PRICE_ORACLES || '{}'); } catch { return {}; } })();
const defaults = { botEnabled:false,botStatus:'Stopped',emergencyStop:false,paperTrading:true,walletAddress:process.env.WALLET_ADDRESS||'',walletBalance:10000,cashBalance:10000,monitoredTokens:envTokens,tokenContracts:{},tokenMeta:{},prices:{BTC:65000,ETH:3500,SOL:150},referencePrices:{BTC:65000,ETH:3500,SOL:150},volumes:{},priceHistory:{},positions:{},tradeHistory:[] };
const clone = x => JSON.parse(JSON.stringify(x)); const ensureDir = () => { if (!fs.existsSync(DATA_DIR)) fs.mkdirSync(DATA_DIR,{recursive:true}); };
function load(){ ensureDir(); if(!fs.existsSync(STORE_PATH)){const s=clone(defaults);fs.writeFileSync(STORE_PATH,JSON.stringify(s,null,2));return s;} try{return {...clone(defaults),...JSON.parse(fs.readFileSync(STORE_PATH,'utf8'))};}catch{return clone(defaults);} }
function save(s){ensureDir();fs.writeFileSync(STORE_PATH,JSON.stringify({...s,paperTrading:true},null,2));}
function norm(s){s.paperTrading=true;s.monitoredTokens=[...new Set((Array.isArray(s.monitoredTokens)?s.monitoredTokens:envTokens).map(x=>String(x).toUpperCase()).filter(x=>/^[A-Z0-9_-]{1,20}$/.test(x)))];s.botStatus=s.botEnabled&&!s.emergencyStop?'Running':'Stopped';s.tokenContracts=s.tokenContracts||{};s.tokenMeta=s.tokenMeta||{};s.prices=s.prices||{};s.referencePrices=s.referencePrices||{};s.volumes=s.volumes||{};s.priceHistory=s.priceHistory||{};s.positions=s.positions||{};s.tradeHistory=Array.isArray(s.tradeHistory)?s.tradeHistory:[];return s;}
function refresh(s){s=norm(s);for(const t of s.monitoredTokens){const old=Number(s.prices[t]||s.referencePrices[t]||1000);const price=Number(Math.max(1e-8,old*(1+Math.random()*.08-.04)).toFixed(8));s.prices[t]=price;s.volumes[t]=Math.round(Math.max(100,(s.volumes[t]||old*100)*(.7+Math.random()*.6)));const h=Array.isArray(s.priceHistory[t])?s.priceHistory[t]:[];h.push({time:Date.now(),price,volume:s.volumes[t]});s.priceHistory[t]=h.slice(-240);}return s;}
function paperTrade(s){return norm(s);}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));}
function chartSvg(symbol,s){const h=(s.priceHistory[symbol]||[]);const W=1200,H=620,pad=70;const values=h.length?h.map(x=>Number(x.price)):([Number(s.prices[symbol]||0)]);const min=Math.min(...values),max=Math.max(...values),range=max-min||Math.max(max*.01,1);const points=values.map((v,i)=>`${pad+(i/Math.max(values.length-1,1))*(W-pad*2)},${H-pad-70-((v-min)/range)*(H-pad*2-80)}`).join(' ');const bars=values.map((_,i)=>{const v=Number(h[i]?.volume||0);const maxV=Math.max(...(h.map(x=>Number(x.volume)||0)),1);return `<rect x="${pad+(i/Math.max(values.length-1,1))*(W-pad*2)-2}" y="${H-pad-(v/maxV)*130}" width="4" height="${(v/maxV)*130}" fill="#334155"/>`;}).join('');return `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}"><rect width="100%" height="100%" rx="24" fill="#0b1020"/><text x="${pad}" y="48" fill="#e2e8f0" font-size="30" font-family="Arial">${esc(symbol)}  •  Arc paper chart</text><text x="${pad}" y="80" fill="#94a3b8" font-size="18" font-family="Arial">Price: ${esc(s.prices[symbol]??'-')}   Volume: ${esc(s.volumes[symbol]??'-')}   Points: ${values.length}</text><line x1="${pad}" y1="${H-pad-70}" x2="${W-pad}" y2="${H-pad-70}" stroke="#334155"/>${bars}<polyline fill="none" stroke="#60a5fa" stroke-width="5" points="${points}"/><text x="${pad}" y="${H-25}" fill="#94a3b8" font-size="16" font-family="Arial">min ${min}  •  max ${max}  •  on-chain metadata / oracle when configured</text></svg>`;}
app.use(express.json({limit:'1mb'}));app.use(express.static(path.join(__dirname,'public')));
app.get('/api/health',(_q,r)=>r.json({ok:true,paperTrading:true,arcReadOnly:true,priceSource:'Arc RPC / configured oracle'}));
app.get('/api/dashboard',(_q,r)=>{const s=norm(load());r.json({...s,tradeHistory:s.tradeHistory.slice(0,20)});});
app.get('/api/prices',(_q,r)=>{const s=norm(load());r.json({prices:s.prices,volumes:s.volumes,priceHistory:s.priceHistory,monitoredTokens:s.monitoredTokens,tokenMeta:s.tokenMeta,tokenContracts:s.tokenContracts});});
app.get('/api/trades',(_q,r)=>r.json({tradeHistory:norm(load()).tradeHistory}));
app.get('/api/config',(_q,r)=>{const s=norm(load());r.json({botEnabled:s.botEnabled,botStatus:s.botStatus,emergencyStop:s.emergencyStop,paperTrading:true,walletAddress:s.walletAddress,monitoredTokens:s.monitoredTokens,tokenContracts:s.tokenContracts,buyThreshold:s.buyThreshold||5,sellThreshold:s.sellThreshold||8,stopLossPct:s.stopLossPct||8,takeProfitPct:s.takeProfitPct||15});});
app.post('/api/config',(q,r)=>{const s=norm(load()),i=q.body||{};if(typeof i.walletAddress==='string'){if(i.walletAddress&&!isAddress(i.walletAddress))return r.status(400).json({error:'Invalid EVM wallet address'});s.walletAddress=i.walletAddress.trim();}if(Array.isArray(i.monitoredTokens))s.monitoredTokens=i.monitoredTokens;save(norm(s));r.json(norm(s));});
app.post('/api/toggle-bot',(q,r)=>{const s=norm(load()),enabled=Boolean(q.body?.enabled);if(enabled&&s.emergencyStop)return r.status(409).json({error:'緊急停止中です'});s.botEnabled=enabled;save(norm(s));r.json({ok:true,botEnabled:s.botEnabled,botStatus:s.botStatus});});
app.post('/api/emergency-stop',(_q,r)=>{const s=norm(load());s.emergencyStop=true;s.botEnabled=false;save(norm(s));r.json({ok:true,emergencyStop:true});});app.post('/api/emergency-reset',(_q,r)=>{const s=norm(load());s.emergencyStop=false;s.botEnabled=false;save(norm(s));r.json({ok:true,emergencyStop:false});});
app.post('/api/refresh-prices',(_q,r)=>{const s=paperTrade(refresh(load()));save(s);r.json({ok:true,prices:s.prices,volumes:s.volumes,priceHistory:s.priceHistory});});
app.post('/api/tokens/import',async(q,r)=>{const address=String(q.body?.address||'').trim();if(!isAddress(address))return r.status(400).json({error:'有効なEVMコントラクトアドレスを入力してください'});try{const meta=await readErc20(address);const symbol=String(q.body?.symbol||meta.symbol).toUpperCase().replace(/[^A-Z0-9_-]/g,'').slice(0,20)||`TOKEN_${address.slice(-4)}`;const s=norm(load());s.monitoredTokens=[...new Set([...s.monitoredTokens,symbol])];s.tokenContracts[symbol]=address;s.tokenMeta[symbol]={...meta,priceSource:oracleMap[symbol]?'Arc Chainlink-compatible oracle':'Arc RPC metadata only',oracleAddress:oracleMap[symbol]||null};if(oracleMap[symbol]){try{s.prices[symbol]=await readChainlinkPrice(oracleMap[symbol]);s.referencePrices[symbol]=s.prices[symbol];}catch(e){s.tokenMeta[symbol].oracleError=e.message;}}s.priceHistory[symbol]=[{time:Date.now(),price:s.prices[symbol]||null,volume:0}];save(s);r.json({ok:true,token:symbol,contractAddress:address,meta:s.tokenMeta[symbol],price:s.prices[symbol]||null});}catch(e){r.status(502).json({error:e.message});}});
app.get('/api/token/:symbol/chart',(q,r)=>{const symbol=String(q.params.symbol).toUpperCase(),s=norm(load());r.json({symbol,contractAddress:s.tokenContracts[symbol]||null,meta:s.tokenMeta[symbol]||null,price:s.prices[symbol]??null,volume:s.volumes[symbol]??null,history:s.priceHistory[symbol]||[]});});
app.get('/api/token/:symbol/chart.svg',(q,r)=>{const symbol=String(q.params.symbol).toUpperCase(),s=norm(load());if(!s.monitoredTokens.includes(symbol))return r.status(404).send('Unknown token');r.type('image/svg+xml').send(chartSvg(symbol,s));});
app.get('/api/arc/status',async(q,r)=>{try{const s=norm(load());r.json(await getArcStatus(q.query.address||s.walletAddress));}catch(e){r.status(503).json({connected:false,network:'Arc',error:e.message});}});
app.get('*',(_q,r)=>r.sendFile(path.join(__dirname,'public','index.html')));setInterval(()=>{const s=norm(load());if(s.botEnabled&&!s.emergencyStop)save(refresh(s));},30000);app.listen(PORT,()=>console.log(`Arc paper trading dashboard running on http://localhost:${PORT}`));module.exports={app,defaults};
