require('dotenv').config();
const express = require('express');
const fs = require('fs');
const path = require('path');
const { getArcStatus, isAddress, readErc20, readChainlinkPrice } = require('./arc-readonly');
const app = express();
const PORT = Number(process.env.PORT || 3000);
const DATA_DIR = path.join(__dirname, 'data');
const STORE_PATH = path.join(DATA_DIR, 'store.json');
const initialTokens = String(process.env.MONITORED_TOKENS || 'BTC,ETH,SOL').split(',').map(x => x.trim().toUpperCase()).filter(Boolean);
const oracleMap = (() => { try { return JSON.parse(process.env.ARC_PRICE_ORACLES || '{}'); } catch { return {}; } })();
const defaults = { botEnabled:false, botStatus:'Stopped', emergencyStop:false, paperTrading:true, walletAddress:process.env.WALLET_ADDRESS || '', walletBalance:10000, cashBalance:10000, monitoredTokens:initialTokens, tokenContracts:{}, tokenMeta:{}, prices:{BTC:65000,ETH:3500,SOL:150}, referencePrices:{BTC:65000,ETH:3500,SOL:150}, volumes:{}, priceHistory:{}, positions:{}, tradeHistory:[] };
const clone = value => JSON.parse(JSON.stringify(value));
function ensureDir() { if (!fs.existsSync(DATA_DIR)) fs.mkdirSync(DATA_DIR, { recursive:true }); }
function load() { ensureDir(); if (!fs.existsSync(STORE_PATH)) { const value=clone(defaults); fs.writeFileSync(STORE_PATH, JSON.stringify(value,null,2)); return value; } try { return { ...clone(defaults), ...JSON.parse(fs.readFileSync(STORE_PATH,'utf8')) }; } catch { return clone(defaults); } }
function save(value) { ensureDir(); fs.writeFileSync(STORE_PATH, JSON.stringify({ ...value, paperTrading:true }, null, 2)); }
function normalize(value) {
  const s = { ...clone(defaults), ...value }; s.paperTrading=true;
  s.monitoredTokens=[...new Set((Array.isArray(s.monitoredTokens)?s.monitoredTokens:initialTokens).map(x=>String(x).trim().toUpperCase()).filter(x=>/^[A-Z0-9_-]{1,20}$/.test(x)))];
  s.botStatus=s.botEnabled&&!s.emergencyStop?'Running':'Stopped'; s.tokenContracts=s.tokenContracts||{}; s.tokenMeta=s.tokenMeta||{}; s.prices=s.prices||{}; s.referencePrices=s.referencePrices||{}; s.volumes=s.volumes||{}; s.priceHistory=s.priceHistory||{}; s.positions=s.positions||{}; s.tradeHistory=Array.isArray(s.tradeHistory)?s.tradeHistory:[]; return s;
}
function refreshPrices(state) { const s=normalize(state); for (const token of s.monitoredTokens) { const old=Number(s.prices[token]||s.referencePrices[token]||1000); const price=Number(Math.max(1e-8,old*(1+Math.random()*.08-.04)).toFixed(8)); s.prices[token]=price; s.volumes[token]=Math.round(Math.max(100,(s.volumes[token]||old*100)*(.7+Math.random()*.6))); const history=Array.isArray(s.priceHistory[token])?s.priceHistory[token]:[]; history.push({time:Date.now(),price,volume:s.volumes[token]}); s.priceHistory[token]=history.slice(-240); } return s; }
function chartSvg(symbol,state) { const s=normalize(state), history=s.priceHistory[symbol]||[], values=history.length?history.map(x=>Number(x.price)).filter(Number.isFinite):[Number(s.prices[symbol]||0)]; const W=1200,H=620,p=70,min=Math.min(...values),max=Math.max(...values),range=max-min||Math.max(max*.01,1),maxVol=Math.max(...history.map(x=>Number(x.volume)||0),1); const xy=(v,i)=>`${p+(i/Math.max(values.length-1,1))*(W-p*2)},${H-p-90-((v-min)/range)*(H-p*2-100)}`; const line=values.map(xy).join(' '); const bars=history.map((x,i)=>`<rect x="${xy(values[i],i).split(',')[0]-2}" y="${H-p-20-(Number(x.volume||0)/maxVol)*120}" width="4" height="${(Number(x.volume||0)/maxVol)*120}" fill="#334155"/>`).join(''); const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c])); return `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}"><rect width="100%" height="100%" rx="24" fill="#0b1020"/><text x="${p}" y="45" fill="#e2e8f0" font-size="30" font-family="Arial">${esc(symbol)} · Arc paper chart</text><text x="${p}" y="78" fill="#94a3b8" font-size="18" font-family="Arial">price ${esc(s.prices[symbol]??'-')} · volume ${esc(s.volumes[symbol]??'-')} · points ${values.length}</text><line x1="${p}" y1="${H-p-90}" x2="${W-p}" y2="${H-p-90}" stroke="#334155"/>${bars}<polyline fill="none" stroke="#60a5fa" stroke-width="5" points="${line}"/><text x="${p}" y="${H-25}" fill="#94a3b8" font-size="16" font-family="Arial">min ${min} · max ${max} · Arc RPC / configured oracle</text></svg>`; }
async function importToken(address, requestedSymbol) { const meta=await readErc20(address); const symbol=String(requestedSymbol||meta.symbol).toUpperCase().replace(/[^A-Z0-9_-]/g,'').slice(0,20)||`TOKEN_${address.slice(-4).toUpperCase()}`; const s=normalize(load()); let key=symbol; if (s.tokenContracts[key] && s.tokenContracts[key].toLowerCase()!==address.toLowerCase()) key=`${symbol}_${address.slice(-4).toUpperCase()}`; s.monitoredTokens=[...new Set([...s.monitoredTokens,key])]; s.tokenContracts[key]=address; s.tokenMeta[key]={...meta,symbol:key,priceSource:oracleMap[key]?'Arc RPC oracle':'Arc RPC metadata only',oracleAddress:oracleMap[key]||null}; if (oracleMap[key]) { s.prices[key]=await readChainlinkPrice(oracleMap[key]); s.referencePrices[key]=s.prices[key]; } if (!s.priceHistory[key]) s.priceHistory[key]=[]; if (!s.priceHistory[key].length) s.priceHistory[key].push({time:Date.now(),price:s.prices[key]||null,volume:0}); save(s); return { token:key, contractAddress:address, meta:s.tokenMeta[key], price:s.prices[key]||null }; }
app.use(express.json({limit:'1mb'})); app.use(express.static(path.join(__dirname,'public')));
app.get('/api/health',(_q,r)=>r.json({ok:true,paperTrading:true,arcReadOnly:true,priceSource:'Arc RPC / configured oracle'}));
app.get('/api/dashboard',(_q,r)=>{const s=normalize(load());r.json({...s,tradeHistory:s.tradeHistory.slice(0,20)});});
app.get('/api/prices',(_q,r)=>{const s=normalize(load());r.json({prices:s.prices,volumes:s.volumes,priceHistory:s.priceHistory,monitoredTokens:s.monitoredTokens,tokenMeta:s.tokenMeta,tokenContracts:s.tokenContracts});});
app.get('/api/trades',(_q,r)=>r.json({tradeHistory:normalize(load()).tradeHistory}));
app.get('/api/config',(_q,r)=>{const s=normalize(load());r.json({botEnabled:s.botEnabled,botStatus:s.botStatus,emergencyStop:s.emergencyStop,paperTrading:true,walletAddress:s.walletAddress,monitoredTokens:s.monitoredTokens,tokenContracts:s.tokenContracts});});
app.post('/api/config',(q,r)=>{const s=normalize(load()),i=q.body||{};if(typeof i.walletAddress==='string'){if(i.walletAddress&&!isAddress(i.walletAddress.trim()))return r.status(400).json({error:'Invalid EVM wallet address'});s.walletAddress=i.walletAddress.trim();}if(Array.isArray(i.monitoredTokens))s.monitoredTokens=i.monitoredTokens;save(normalize(s));r.json(normalize(s));});
app.post('/api/toggle-bot',(q,r)=>{const s=normalize(load()),enabled=Boolean(q.body&&q.body.enabled!==undefined?q.body.enabled:!s.botEnabled);if(enabled&&s.emergencyStop)return r.status(409).json({error:'緊急停止中です。先にリセットしてください。'});s.botEnabled=enabled;save(normalize(s));r.json({ok:true,botEnabled:s.botEnabled,botStatus:s.botStatus});});
app.post('/api/emergency-stop',(_q,r)=>{const s=normalize(load());s.emergencyStop=true;s.botEnabled=false;save(s);r.json({ok:true,emergencyStop:true,botStatus:s.botStatus});});
app.post('/api/emergency-reset',(_q,r)=>{const s=normalize(load());s.emergencyStop=false;s.botEnabled=false;save(s);r.json({ok:true,emergencyStop:false,botStatus:s.botStatus});});
app.post('/api/refresh-prices',(_q,r)=>{const s=refreshPrices(load());save(s);r.json({ok:true,prices:s.prices,volumes:s.volumes,priceHistory:s.priceHistory});});
app.post('/api/tokens/import',async(q,r)=>{const address=String(q.body?.address||'').trim();if(!isAddress(address))return r.status(400).json({error:'有効なEVMコントラクトアドレスを入力してください'});try{r.json({ok:true,...await importToken(address,q.body?.symbol)});}catch(e){r.status(502).json({error:e.message});}});
app.get('/api/token/:symbol/chart',(q,r)=>{const symbol=String(q.params.symbol).toUpperCase(),s=normalize(load());if(!s.monitoredTokens.includes(symbol))return r.status(404).json({error:'Unknown token'});r.json({symbol,contractAddress:s.tokenContracts[symbol]||null,meta:s.tokenMeta[symbol]||null,price:s.prices[symbol]??null,volume:s.volumes[symbol]??null,history:s.priceHistory[symbol]||[]});});
app.get('/api/token/:symbol/chart.svg',(q,r)=>{const symbol=String(q.params.symbol).toUpperCase(),s=normalize(load());if(!s.monitoredTokens.includes(symbol))return r.status(404).send('Unknown token');r.type('image/svg+xml').send(chartSvg(symbol,s));});
app.get('/api/arc/status',async(q,r)=>{try{const s=normalize(load());r.json(await getArcStatus(q.query.address||s.walletAddress));}catch(e){r.status(503).json({connected:false,network:'Arc',error:e.message});}});
app.get('*',(_q,r)=>r.sendFile(path.join(__dirname,'public','index.html')));
setInterval(()=>{const s=normalize(load());if(s.botEnabled&&!s.emergencyStop)save(refreshPrices(s));},30000);
app.listen(PORT,()=>console.log(`Arc paper trading dashboard running on http://localhost:${PORT}`));
module.exports={app,defaults};
