const express = require('express');
const fs = require('fs');
const path = require('path');
require('dotenv').config();
const { getArcStatus, isAddress } = require('./arc-readonly');

const app = express();
const PORT = Number(process.env.PORT || 3000);
const DATA_DIR = path.join(__dirname, 'data');
const STORE_PATH = path.join(DATA_DIR, 'store.json');
const envTokens = String(process.env.MONITORED_TOKENS || 'BTC,ETH,SOL').split(',');
const defaultConfig = {
  botEnabled:false, botStatus:'Stopped', emergencyStop:false, paperTrading:true,
  walletAddress:process.env.WALLET_ADDRESS || '', walletBalance:10000, cashBalance:10000,
  monitoredTokens:envTokens.map((v)=>v.trim().toUpperCase()).filter(Boolean),
  tokenContracts:{}, tokenMeta:{}, buyThreshold:Number(process.env.BUY_CONDITION_PERCENT||5), sellThreshold:Number(process.env.SELL_CONDITION_PERCENT||8),
  stopLossPct:Number(process.env.STOP_LOSS_PERCENT||8), takeProfitPct:Number(process.env.TAKE_PROFIT_PERCENT||15), maxPurchaseAmount:Number(process.env.MAX_PURCHASE_AMOUNT||500),
  prices:{BTC:65000,ETH:3500,SOL:150}, referencePrices:{BTC:65000,ETH:3500,SOL:150}, volumes:{}, priceHistory:{}, positions:{}, tradeHistory:[], social:{},
};
function clone(v){return JSON.parse(JSON.stringify(v));} function ensureDir(){if(!fs.existsSync(DATA_DIR))fs.mkdirSync(DATA_DIR,{recursive:true});}
function number(v,f,min=0,max=1e9){const n=Number(v);return Number.isFinite(n)?Math.min(max,Math.max(min,n)):f;}
function tokens(v){const a=(Array.isArray(v)?v:defaultConfig.monitoredTokens).map(x=>String(x).trim().toUpperCase()).filter(x=>/^[A-Z0-9_-]{1,20}$/.test(x));return [...new Set(a.length?a:defaultConfig.monitoredTokens)];}
function load(){ensureDir();if(!fs.existsSync(STORE_PATH)){const s=clone(defaultConfig);fs.writeFileSync(STORE_PATH,JSON.stringify(s,null,2));return s;}try{return {...clone(defaultConfig),...JSON.parse(fs.readFileSync(STORE_PATH,'utf8'))};}catch{return clone(defaultConfig);}}
function save(s){ensureDir();fs.writeFileSync(STORE_PATH,JSON.stringify({...s,paperTrading:true},null,2));}
function normalize(s){s.paperTrading=true;s.monitoredTokens=tokens(s.monitoredTokens);s.botStatus=s.botEnabled&&!s.emergencyStop?'Running':'Stopped';for(const k of ['walletBalance','cashBalance'])s[k]=number(s[k],10000);for(const k of ['buyThreshold','sellThreshold','stopLossPct','takeProfitPct'])s[k]=number(s[k],defaultConfig[k],0,100);s.maxPurchaseAmount=number(s.maxPurchaseAmount,500,0,1e7);s.tradeHistory=Array.isArray(s.tradeHistory)?s.tradeHistory:[];s.positions=s.positions||{};s.volumes=s.volumes||{};s.priceHistory=s.priceHistory||{};s.tokenContracts=s.tokenContracts||{};s.tokenMeta=s.tokenMeta||{};return s;}
function refreshMarket(s){s=normalize(s);const now=Date.now();for(const t of s.monitoredTokens){const current=Number(s.prices[t]||s.referencePrices[t]||1000);const price=Number(Math.max(.00000001,current*(1+Math.random()*.08-.04)).toFixed(8));s.prices[t]=price;s.volumes[t]=Math.round(Math.max(1000,(s.volumes[t]||current*100)*(.7+Math.random()*.6)));const h=Array.isArray(s.priceHistory[t])?s.priceHistory[t]:[];h.push({time:now,price,volume:s.volumes[t]});s.priceHistory[t]=h.slice(-120);}return s;}
function paperTrade(s){s=normalize(s);if(!s.botEnabled||s.emergencyStop)return s;for(const t of s.monitoredTokens){const price=Number(s.prices[t]),ref=Number(s.referencePrices[t]||price),old=s.positions[t]||{quantity:0,entryPrice:0},p={...old},change=((price-ref)/ref)*100;let action=null,quantity=0;if(!p.quantity&&change<=-s.buyThreshold&&s.cashBalance>0){const amount=Math.min(s.maxPurchaseAmount,s.cashBalance);quantity=Number((amount/price).toFixed(8));p.quantity=quantity;p.entryPrice=price;s.cashBalance-=amount;action='BUY';}else if(p.quantity&&(change>=s.sellThreshold||change<=-s.stopLossPct||price>=p.entryPrice*(1+s.takeProfitPct/100))){quantity=p.quantity;s.cashBalance+=quantity*price;s.walletBalance+=quantity*(price-p.entryPrice);action=change<=-s.stopLossPct?'STOP_LOSS':'TAKE_PROFIT';p.quantity=0;p.entryPrice=0;}s.positions[t]=p;if(action)s.tradeHistory.unshift({timestamp:new Date().toISOString(),token:t,action,side:action==='BUY'?'BUY':'SELL',price,quantity});}s.tradeHistory=s.tradeHistory.slice(0,200);return s;}
async function dexToken(address){const url=`https://api.dexscreener.com/latest/dex/tokens/${address}`;const r=await fetch(url);if(!r.ok)throw new Error(`DEX Screener HTTP ${r.status}`);const body=await r.json();const pairs=(body.pairs||[]).filter(p=>!process.env.ARC_DEX_CHAIN_ID||p.chainId===process.env.ARC_DEX_CHAIN_ID);if(!pairs.length)throw new Error('このコントラクトの対応ペアが見つかりません。チェーン設定を確認してください。');const pair=pairs.sort((a,b)=>(Number(b.liquidity?.usd)||0)-(Number(a.liquidity?.usd)||0))[0];return {address,chainId:pair.chainId,dexId:pair.dexId,symbol:pair.baseToken?.symbol||'TOKEN',name:pair.baseToken?.name||'Unknown token',pairAddress:pair.pairAddress,priceUsd:Number(pair.priceUsd)||0,volume24h:Number(pair.volume?.h24)||0,liquidityUsd:Number(pair.liquidity?.usd)||0,url:pair.url||null,updatedAt:new Date().toISOString()};}
function xQueryFor(token){return `(${token} OR $${token}) -is:retweet lang:ja`;}
async function fetchXBuzz(token){const bearer=String(process.env.X_BEARER_TOKEN||'').trim();if(!bearer)return{configured:false,token,score:null,posts:null,message:'X_BEARER_TOKEN未設定'};const u=new URL('https://api.twitter.com/2/tweets/search/recent');u.searchParams.set('query',xQueryFor(token));u.searchParams.set('max_results','100');u.searchParams.set('tweet.fields','public_metrics,created_at');const r=await fetch(u,{headers:{Authorization:`Bearer ${bearer}`}});if(!r.ok)throw new Error(`X API HTTP ${r.status}`);const b=await r.json(),tweets=b.data||[];let likes=0,reposts=0,replies=0,quotes=0;for(const t of tweets){const m=t.public_metrics||{};likes+=m.like_count||0;reposts+=m.retweet_count||0;replies+=m.reply_count||0;quotes+=m.quote_count||0;}const score=Math.min(100,Math.round(Math.log10(1+tweets.length*10+likes+reposts*2+replies+quotes*2)*12));return{configured:true,token,score,posts:tweets.length,likes,reposts,replies,quotes,sampleSize:tweets.length,fetchedAt:new Date().toISOString()};}
if(String(process.env.APP_MODE||'paper').toLowerCase()!=='paper'||String(process.env.PAPER_TRADING||'true').toLowerCase()!=='true')throw new Error('Safety lock: APP_MODE=paper and PAPER_TRADING=true are required.');
app.use(express.json({limit:'1mb'}));app.use(express.static(path.join(__dirname,'public')));
app.get('/api/health',(_q,r)=>r.json({ok:true,mode:'paper-trading',paperTrading:true,arcReadOnly:true,xConfigured:Boolean(process.env.X_BEARER_TOKEN)}));
app.get('/api/dashboard',(_q,r)=>{const s=normalize(load());r.json({...s,tradeHistory:s.tradeHistory.slice(0,20)});});
app.get('/api/config',(_q,r)=>{const s=normalize(load());r.json({botEnabled:!!s.botEnabled,botStatus:s.botStatus,emergencyStop:!!s.emergencyStop,paperTrading:true,walletAddress:s.walletAddress,monitoredTokens:s.monitoredTokens,tokenContracts:s.tokenContracts,buyThreshold:s.buyThreshold,sellThreshold:s.sellThreshold,stopLossPct:s.stopLossPct,takeProfitPct:s.takeProfitPct,maxPurchaseAmount:s.maxPurchaseAmount});});
app.post('/api/config',(q,r)=>{const s=normalize(load()),i=q.body||{};if(typeof i.walletAddress==='string'){if(i.walletAddress&&!isAddress(i.walletAddress.trim()))return r.status(400).json({error:'Invalid EVM wallet address'});s.walletAddress=i.walletAddress.trim();}if(i.monitoredTokens!==undefined)s.monitoredTokens=tokens(i.monitoredTokens);for(const k of ['buyThreshold','sellThreshold','stopLossPct','takeProfitPct','maxPurchaseAmount'])if(i[k]!==undefined)s[k]=number(i[k],s[k],0,k==='maxPurchaseAmount'?1e7:100);save(normalize(s));r.json(normalize(s));});
app.post('/api/toggle-bot',(q,r)=>{const s=normalize(load()),enabled=Boolean(q.body&&q.body.enabled!==undefined?q.body.enabled:!s.botEnabled);if(enabled&&s.emergencyStop)return r.status(409).json({error:'緊急停止中です。先にリセットしてください。'});s.botEnabled=enabled;save(normalize(s));r.json({ok:true,botEnabled:s.botEnabled,botStatus:s.botStatus});});
app.post('/api/emergency-stop',(_q,r)=>{const s=normalize(load());s.emergencyStop=true;s.botEnabled=false;save(normalize(s));r.json({ok:true,emergencyStop:true,botStatus:s.botStatus});});app.post('/api/emergency-reset',(_q,r)=>{const s=normalize(load());s.emergencyStop=false;s.botEnabled=false;save(normalize(s));r.json({ok:true,emergencyStop:false,botStatus:s.botStatus});});
app.post('/api/refresh-prices',(_q,r)=>{const s=paperTrade(refreshMarket(load()));save(s);r.json({ok:true,prices:s.prices,volumes:s.volumes,priceHistory:s.priceHistory,positions:s.positions,tradeHistory:s.tradeHistory.slice(0,10)});});
app.get('/api/prices',(_q,r)=>{const s=normalize(load());r.json({prices:s.prices,volumes:s.volumes,priceHistory:s.priceHistory,monitoredTokens:s.monitoredTokens,tokenMeta:s.tokenMeta,tokenContracts:s.tokenContracts});});
app.get('/api/trades',(_q,r)=>r.json({tradeHistory:normalize(load()).tradeHistory}));
app.post('/api/tokens/import',async(q,r)=>{const address=String(q.body?.address||'').trim();if(!isAddress(address))return r.status(400).json({error:'有効なEVMコントラクトアドレスを入力してください'});try{const meta=await dexToken(address);const s=normalize(load());let symbol=String(q.body?.symbol||meta.symbol).toUpperCase().replace(/[^A-Z0-9_-]/g,'').slice(0,20)||'TOKEN';if(s.monitoredTokens.includes(symbol)&&s.tokenContracts[symbol]&&s.tokenContracts[symbol].toLowerCase()!==address.toLowerCase())symbol=`${symbol}_${address.slice(-4).toUpperCase()}`;s.monitoredTokens=[...new Set([...s.monitoredTokens,symbol])];s.tokenContracts[symbol]=address;s.tokenMeta[symbol]={...meta,symbol};s.prices[symbol]=meta.priceUsd||1000;s.referencePrices[symbol]=s.prices[symbol];s.volumes[symbol]=meta.volume24h||0;s.priceHistory[symbol]=[{time:Date.now(),price:s.prices[symbol],volume:s.volumes[symbol]}];save(s);r.json({ok:true,token:symbol,contractAddress:address,meta});}catch(e){r.status(502).json({error:e.message});}});
app.delete('/api/tokens/:symbol', (q,r)=>{const symbol=String(q.params.symbol).toUpperCase(),s=normalize(load());if(!s.monitoredTokens.includes(symbol))return r.status(404).json({error:'トークンが見つかりません'});s.monitoredTokens=s.monitoredTokens.filter(t=>t!==symbol);delete s.tokenContracts[symbol];delete s.tokenMeta[symbol];save(s);r.json({ok:true,monitoredTokens:s.monitoredTokens});});
app.get('/api/token/:symbol/chart',(q,r)=>{const symbol=String(q.params.symbol).toUpperCase(),s=normalize(load());r.json({symbol,contractAddress:s.tokenContracts[symbol]||null,price:s.prices[symbol]??null,volume:s.volumes[symbol]??null,history:s.priceHistory[symbol]||[],meta:s.tokenMeta[symbol]||null});});
app.get('/api/social',async(q,r)=>{const s=normalize(load()),requested=q.query.token?[String(q.query.token).toUpperCase()]:s.monitoredTokens;try{const results={};for(const token of requested.slice(0,10)){const queryToken=s.tokenMeta[token]?.symbol||token;results[token]=await fetchXBuzz(queryToken);}r.json({source:'X API v2 recent search',results});}catch(e){r.status(502).json({error:e.message,source:'X API v2 recent search'});}});
app.get('/api/arc/status',async(q,r)=>{try{const s=normalize(load()),address=q.query.address||s.walletAddress;if(address&&!isAddress(address))return r.status(400).json({error:'Invalid EVM wallet address'});r.json(await getArcStatus(address));}catch(e){r.status(503).json({connected:false,network:'Arc',error:e.message});}});
app.get('*',(_q,r)=>r.sendFile(path.join(__dirname,'public','index.html')));setInterval(()=>{const s=normalize(load());if(s.botEnabled&&!s.emergencyStop)save(paperTrade(refreshMarket(s)));},30000);app.listen(PORT,()=>console.log(`Arc paper trading dashboard running on http://localhost:${PORT}`));module.exports={app,defaultConfig};
